spring.application.name=JwtSpringBootProject
server.port=8080

# logging level ??
logging.level.kr.or.ddit=debug
logging.level.org.springframework.security=debug
logging.level.p6spy=debug

#jsp ??
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

# ?? ??? ?, ??
# ???? ?? ?? ???(??? true), ?? ??? ??? true??? ??
# spring.servlet.multipart.enabled=true
# ??? ??? ?? ?? ??(? ??), ???? 1MB
spring.servlet.multipart.max-file-size=10MB
# ??? ?? ?? ??+???? ?? ??, ???? 10MB
spring.servlet.multipart.max-request-size=20MB
# ?? ??? ?, ??? ??? ??
spring.servlet.multipart.file-size-threshold=20MB
server.tomcat.max-part-count=30
upload_profile_path=C:/upload/blog/profile
upload_blog_path=C:/upload/blog
# spring.servlet.multipart.location - ?? ??? ?, ??? ?? ?? ??
# Part? ?? ?? ??
# Tomcat ?? 9.0.106 ??, ?? Spring Boot 3.4.7 ?? CVE-2025-48988? ?? ?? ??? ???
# maxPartCount?? ??? ?????, ? ???? 10?? ???. ??? ??? ??? ??? ??? ??? ???
# ???? ???? ??? Part? ??? ???. (???, ????, ???? ??? ?? Part? ??? ???)
# SpringBoot 3.4.7 ?? ???? Release ??? ??? ???? ?? ??? ??? ????? ??
# spring.servlet.multipart.max-file-count=10

# ?????? ?? ?? ??(datasource)
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/xe
spring.datasource.username=boot
spring.datasource.password=java
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# mybatis ??
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.configuration.jdbc-type-for-null=varchar
mybatis.type-aliases-package=kr.or.ddit.vo
mybatis.mapper-locations=classpath:mybatis/mapper/*_Mapper.xml

# JWT ??
# ?? ???
kr.or.ddit.jwt.issuer=ddit
# jwt secret key
kr.or.ddit.jwt.secret_key=springboot2